spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



